restartc:
	sh tomcat/bin/shutdown.sh
	sh tomcat/bin/compile.sh
	sh tomcat/bin/startup.sh
restart:
	sh tomcat/bin/shutdown.sh
	sh tomcat/bin/startup.sh
start:
	sh tomcat/bin/startup.sh
stop:
	sh tomcat/bin/shutdown.sh